version: "3"

services:
  api:
    build: .
    image: sun-monitor-api:latest
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - my-network
  database:
    image: mongo
    ports:
      - "27015:27017"
    volumes:
      - data:/data/db
    networks:
      - my-network
volumes:
  data:

networks:
  my-network:
    driver: bridge